---
title: "Create Spatial Subset"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{obisindicators}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## use data

```{r}
librarian::shelf(arrow, dplyr, here, readr)

occ <- open_dataset(here("data/obis_20220404.parquet"))
occ <- occ %>%
  select(decimalLongitude, decimalLatitude, species) %>%    # drop unnecessary columns 
  group_by(decimalLongitude, decimalLatitude, species) %>%  # remove dulplicate rows
  collect() %>%
  summarize(records = n())
write_csv(occ, "data/occ.csv")

# write full regional occurrence dataset
# [Marine Regions · South Atlantic Ocean (IHO Sea Area)](https://marineregions.org/gazetteer.php?p=details&id=1914)
# Min. Lat	60° 0' 0" S (-60°)  
# Min. Long	69° 36' 3" W (-69.6008°)  
# Max. Lat	0° 4' 30.4" N (0.0751°)  
# Max. Long	20° 0' 32.6" E (20.0091°)  
occ %>% 
  filter(
    lat >= -60,
    lon >= -69.6008,
    lat <= 0.0751,
    lon <= 20.0091) %>% 
  sample_n(1000000) %>% 
  write_parquet(occ, "data/occ_SAtlantic.parquet")
```
