---
title: "Temporal Subsets"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Temporal Subsets}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Create a discrete global grid

Create an ISEA discrete global grid of resolution 9 using the [dggridR](https://github.com/r-barnes/dggridR) package:

```{r dgconstruct}
library(dggridR) # remotes::install_github("r-barnes/dggridR")

dggs <- dgconstruct(projection = "ISEA", topology = "HEXAGON", res = 5)
```

Then assign cell numbers to the occurrence data:

```{r dgGEO_to_SEQNUM}
library(obisindicators)
occ_1960s$cell <- dgGEO_to_SEQNUM(
  dggs, occ_1960s$decimalLongitude, 
  occ_1960s$decimalLatitude)[["seqnum"]]
occ_1970s$cell <- dgGEO_to_SEQNUM(
  dggs, occ_1970s$decimalLongitude, 
  occ_1970s$decimalLatitude)[["seqnum"]]
occ_1980s$cell <- dgGEO_to_SEQNUM(
  dggs, occ_1980s$decimalLongitude, 
  occ_1980s$decimalLatitude)[["seqnum"]]
occ_1990s$cell <- dgGEO_to_SEQNUM(
  dggs, occ_1990s$decimalLongitude, 
  occ_1990s$decimalLatitude)[["seqnum"]]
occ_2000s$cell <- dgGEO_to_SEQNUM(
  dggs, occ_2000s$decimalLongitude, 
  occ_2000s$decimalLatitude)[["seqnum"]]
occ_2010s$cell <- dgGEO_to_SEQNUM(
  dggs, occ_2010s$decimalLongitude, 
  occ_2010s$decimalLatitude)[["seqnum"]]

```

## Calculate metrics

```{r calc_es50}
metrics_1960s <- calc_es50(occ_1960s)
metrics_1970s <- calc_es50(occ_1970s)
metrics_1980s <- calc_es50(occ_1980s)
metrics_1990s <- calc_es50(occ_1990s)
metrics_2000s <- calc_es50(occ_2000s)
metrics_2010s <- calc_es50(occ_2010s)
```

Add cell geometries to the metrics table:

```{r dgcellstogrid}
library(sf)

grid_1960s <- dgcellstogrid(dggs, metrics_1960s$cell) %>% 
  st_wrap_dateline() %>% 
  rename(cell = seqnum) %>% 
  left_join(
    metrics_1960s,
    by = "cell")
grid_1970s <- dgcellstogrid(dggs, grid_1970s$cell) %>% 
  st_wrap_dateline() %>% 
  rename(cell = seqnum) %>% 
  left_join(
    metrics_1970s,
    by = "cell")
grid_1980s <- dgcellstogrid(dggs, grid_1980s$cell) %>% 
  st_wrap_dateline() %>% 
  rename(cell = seqnum) %>% 
  left_join(
    metrics_1980s,
    by = "cell")
grid_1990s <- dgcellstogrid(dggs, grid_1990s$cell) %>% 
  st_wrap_dateline() %>% 
  rename(cell = seqnum) %>% 
  left_join(
    metrics_1990s,
    by = "cell")
grid_2000s <- dgcellstogrid(dggs, grid_2000s$cell) %>% 
  st_wrap_dateline() %>% 
  rename(cell = seqnum) %>% 
  left_join(
    metrics_2000s,
    by = "cell")
grid_2010s <- dgcellstogrid(dggs, grid_2010s$cell) %>% 
  st_wrap_dateline() %>% 
  rename(cell = seqnum) %>% 
  left_join(
    metrics_2010s,
    by = "cell")
```

## Plot maps

Let's look at the resulting metrics in map form.

```{r map_gcs}
gmap_metric(grid_1960s, "es", label = "1960s ES(50)")
gmap_metric(grid_1970s, "es", label = "1970s ES(50)")
gmap_metric(grid_1980s, "es", label = "1980s ES(50)")
gmap_metric(grid_1990s, "es", label = "1990s ES(50)")
gmap_metric(grid_2000s, "es", label = "2000s ES(50)")
gmap_metric(grid_2010s, "es", label = "2010s ES(50)")

```
