-- Reference: the global OBIS -> H3 DuckDB build, as generated by
-- obisindicators::build_obis_h3_duckdb(src = "s3://obis-open-data/occurrence/*.parquet").
-- Run by the R driver via DBI::dbExecute(); kept here as the canonical,
-- human-readable statement of the build. Indicator math = SQL translation of
-- calc_indicators() (esn = 50). For a demo region, add a bbox predicate to the
-- WHERE of step 1 (decimalLongitude/Latitude BETWEEN ...).

INSTALL httpfs;            LOAD httpfs;
INSTALL h3 FROM community; LOAD h3;
INSTALL spatial;           LOAD spatial;
SET s3_region = 'us-east-1';
SET s3_access_key_id = ''; SET s3_secret_access_key = '';   -- anonymous public bucket

-- 1. stream parquet -> species-level base table at the finest resolution (7)
CREATE TABLE occ_h3_base AS
SELECT
  CAST(h3_latlng_to_cell(decimalLatitude, decimalLongitude, 7) AS BIGINT) AS cell_id,
  CAST(aphiaid AS BIGINT) AS aphiaid,
  phylum, class, "order", family, genus, species,
  CAST(date_year AS SMALLINT) AS date_year,
  COUNT(*) AS records
FROM read_parquet('s3://obis-open-data/occurrence/*.parquet', union_by_name = true)
WHERE species IS NOT NULL
  AND decimalLatitude  IS NOT NULL
  AND decimalLongitude IS NOT NULL
  AND dropped IS NOT TRUE
  AND absence IS NOT TRUE
GROUP BY ALL;

-- 2. unified species-level store across resolution tiers 3 / 5 / 7
CREATE TABLE occ_h3 (
  res UTINYINT, cell_id BIGINT, aphiaid BIGINT,
  phylum VARCHAR, class VARCHAR, "order" VARCHAR, family VARCHAR,
  genus VARCHAR, species VARCHAR, date_year SMALLINT, records BIGINT);

INSERT INTO occ_h3   -- res 7 (base)
SELECT 7, cell_id, aphiaid, phylum, class, "order", family, genus, species,
       date_year, SUM(records) FROM occ_h3_base GROUP BY ALL;
INSERT INTO occ_h3   -- res 5
SELECT 5, CAST(h3_cell_to_parent(cell_id, 5) AS BIGINT), aphiaid, phylum, class,
       "order", family, genus, species, date_year, SUM(records)
FROM occ_h3_base GROUP BY ALL;
INSERT INTO occ_h3   -- res 3
SELECT 3, CAST(h3_cell_to_parent(cell_id, 3) AS BIGINT), aphiaid, phylum, class,
       "order", family, genus, species, date_year, SUM(records)
FROM occ_h3_base GROUP BY ALL;

-- 3. precomputed all-taxa indicators for res 1..7 (repeat per resolution {r})
CREATE TABLE idx_h3 (
  res UTINYINT, cell_id BIGINT, n BIGINT, sp BIGINT,
  shannon DOUBLE, simpson DOUBLE, es DOUBLE);

-- for each r in 1..7:
INSERT INTO idx_h3
WITH src AS (
  SELECT CAST(h3_cell_to_parent(cell_id, {r}) AS BIGINT) AS cell_id,
         species, SUM(records) AS ni
  FROM occ_h3 WHERE res = 7 GROUP BY 1, 2),
tot AS (SELECT cell_id, SUM(ni) AS n FROM src GROUP BY cell_id),
per AS (
  SELECT s.cell_id, s.ni, t.n,
    CASE
      WHEN t.n - s.ni >= 50 THEN 1 - exp(
             lgamma(t.n - s.ni + 1) + lgamma(t.n - 50 + 1)
           - lgamma(t.n - s.ni - 50 + 1) - lgamma(t.n + 1))
      WHEN t.n >= 50 THEN 1
      ELSE NULL END AS esi
  FROM src s JOIN tot t USING (cell_id))
SELECT {r} AS res, cell_id,
  ANY_VALUE(n)                                AS n,
  COUNT(*)                                    AS sp,
  -SUM((ni::DOUBLE / n) * ln(ni::DOUBLE / n)) AS shannon,
  SUM((ni::DOUBLE / n) * (ni::DOUBLE / n))    AS simpson,
  SUM(esi)                                    AS es
FROM per GROUP BY cell_id;

DROP TABLE occ_h3_base;
CHECKPOINT;
