-- Reference: the served h3t tile-query templates, as generated by
-- obisindicators::obis_h3t_sql(). The `h3t` service base64-decodes one of
-- these from the tile URL `?q=`, validates it is SELECT-only (project exactly
-- cell_id, value, n), substitutes {{res}} with the tile's H3 resolution, wraps
-- it with a centroid bbox filter + row cap, and returns h3j JSON.
--
-- The client SQL carries NO bbox. The server prunes each tile automatically: it
-- derives the tile's covering res-3 H3 cells from z/x/y and rewrites the query's
-- AST to add, to any scan of a table carrying `hex_prune`:
--   AND <table>.hex_prune IN (<covering res-3 cell ids>)
-- occ_h3/idx_h3 are clustered by (res, hex_prune, cell_id), so this prunes row
-- groups to the tile. The stats route and direct (/h3 API) callers never inject.
-- obis_h3t_sql() is the single source of truth; these are illustrative (shown
-- WITHOUT the server-injected hex_prune predicate).

-- ============================================================ default (all taxa)
-- fast path: precomputed idx_h3. indicator col es | sp | shannon | n.
SELECT cell_id, es      AS value, n FROM idx_h3 WHERE res = LEAST({{res}}, 7);  -- ES50
SELECT cell_id, sp      AS value, n FROM idx_h3 WHERE res = LEAST({{res}}, 7);  -- richness
SELECT cell_id, shannon AS value, n FROM idx_h3 WHERE res = LEAST({{res}}, 7);  -- Shannon
SELECT cell_id, n       AS value, n FROM idx_h3 WHERE res = LEAST({{res}}, 7);  -- # records

-- ===================================================== filtered (taxon / year)
-- live computation over the species-level occ_h3 store. the `src` CTE picks the
-- resolution tier (3/5/7) matching the tile zoom and rolls cells up to {{res}};
-- the server injects hex_prune into this occ_h3 scan. example: ES50 for
-- class = 'Aves', years 2000-2020.
WITH src AS (
  SELECT CAST(h3_cell_to_parent(cell_id,
           LEAST({{res}}, CASE WHEN {{res}} <= 3 THEN 3
                               WHEN {{res}} <= 5 THEN 5 ELSE 7 END)) AS BIGINT) AS cell_id,
         species, SUM(records) AS ni
  FROM occ_h3
  WHERE res = CASE WHEN {{res}} <= 3 THEN 3 WHEN {{res}} <= 5 THEN 5 ELSE 7 END
    AND "class" = 'Aves'
    AND date_year >= 2000
    AND date_year <= 2020
  GROUP BY 1, 2),
tot AS (SELECT cell_id, SUM(ni) AS n FROM src GROUP BY cell_id),
per AS (
  SELECT s.cell_id, s.ni, t.n,
    CASE
      WHEN t.n - s.ni >= 50 THEN 1 - exp(
             lgamma(t.n - s.ni + 1) + lgamma(t.n - 50 + 1)
           - lgamma(t.n - s.ni - 50 + 1) - lgamma(t.n + 1))
      WHEN t.n >= 50 THEN 1
      ELSE NULL END AS esi
  FROM src s JOIN tot t USING (cell_id))
SELECT cell_id, SUM(esi) AS value, ANY_VALUE(n) AS n
FROM per GROUP BY cell_id;
